---
- name: restart loki
  systemd:
    daemon_reload: true
    name: loki
    state: restarted
  become: true
  tags: loki

- name: reload loki
  systemd:
    name: loki
    state: reloaded
  become: true
  tags: loki

- name: reload ufw
  systemd:
    name: ufw
    state: reloaded
  tags: loki
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags: loki
  become: true