---
- name: restart loki
  systemd:
    daemon_reload: true
    name: loki
    state: restarted
  become: true
  tags: loki

- name: reload loki
  systemd:
    name: loki
    state: reloaded
  become: true
  tags: loki